### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by georgefst** [antiantisepticeye/vscode-color-picker#1]
Some minimal documentation would go a long way. In particular, to make this work for some language, say Haskell, it's necessary to:
- Add a `vscode-color-picker.languages` entry in `settings.json`, with its value a list containing VSCode's identifier string for the language, e.g. `["python", "haskell"]`.
- Reload the VSCode editor window.
- Open a Haskell source file. The color picker will appear when hovering over any sequence of characters beginning with a `#` followed by at least 6 hex characters, e.g. `#00a2ffff`. This will be interpreted as an RGB specification of a colour (or RGBA if there are at least 8 characters). The colour corresponding to those characters will also appear to the left of them in the editor.

**Comment by antiantisepticeye** [comment]
added documentation! 👍
